MVC/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Akka.Actor;
using MVC.Actor;
using MVC.Models;
using Util;

namespace MVC.Controllers
{
    public class DataController : Controller
    {
        // GET: Data
        [HttpPost]
        public JsonResult Save( )
        {
            return Json("Ok");
        }

        [HttpPost]
        public JsonResult Update()
        {
            return Json("Ok");
        }

        [HttpPost]
        public JsonResult Delete()
        {
            return Json("Ok");
        }

        [HttpPost]
        public JsonResult Select(string search, string tableName, string fieldName)
        {
            //
            //
            DataTable dt = new DataTable("Test");
            SystemActors.SignalRActor.Tell(dt, ActorRefs.Nobody);
            List<DrowDownItem> _DropdownList = new List<DrowDownItem>();
            _DropdownList.Add(new DrowDownItem() { id = "A", text = "Apple" + Session["Token"] });
            _DropdownList.Add(new DrowDownItem() { id = "B", text = "Boy" + Session["Token"] });
          return Json(_DropdownList);
        }

        [HttpPost]
        public ActionResult SendRequest()
        {
            DataTable dt = new DataTable("Test");
            SystemActors.SignalRActor.Tell(dt, ActorRefs.Nobody);
            return new EmptyResult();
        }
    }
}

MVC/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
using Util;
namespace MVC.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        // GET: Data
        [HttpPost]
        public JsonResult Save( Dictionary<string, string> valueDic)
        {
            return Json("Ok");
        }

        public ActionResult Index()
        {
            UserSetting usersetting = new UserSetting();
            usersetting.Menu = new TreeNode("Test");
            List<ControlModel> _controls = new List<ControlModel>();
            _controls.Add(new InputModel() { Label = "Testlabel", Value = "Test Label", PlaceHolder = "Please enter key", Icon = "fa fa-user" });
            _controls.Add(new InputModel() { Label = "Testlabel", Value = "Test Label", PlaceHolder = "Please enter key", Icon = "fa fa-user" });
            _controls.Add(new InputModel() { Label = "Testlabel", Value = "Test Label", PlaceHolder = "Please enter key", Icon = "fa fa-user" });
            _controls.Add(new DropdownModel(){Label = "Test",Value = "Test",FieldName = "Test",TableName ="Test",SelectMode = "select2"});
            ViewBag.Controls = _controls;
            //sersetting.Menu = new TreeNode("Test");
            return View("Menu", usersetting);
        }
    }
}

MVC/Views/Menu/Menu.cshtml
@using System.Data.Entity.ModelConfiguration.Configuration
@using MVC.Models
@model MVC.Models.UserSetting
@{
    ViewBag.Title = "Menu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="Menu">

</div>
@Html.Partial("HorizontalFormViewPartial",(List<ControlModel>)ViewBag.Controls)

@section scripts
{

    <script>
    $(document).ready(function() {

        populateMenuList();

    });


    function populateMenuList() {
        var node = @Html.Raw(Json.Encode(Model.Menu));
      
            $.ajax({
                url: '@Url.Action("Save","Data")',
            type: "Post",
            data: {},
            success:function(data) {

            },
            error: function(data) {

            }

        });

        $("#Menu").on('changed.jstree', function(e, data) {

        }).jstree({
            "core": {
                "themes": {
                    "responsive": false
                },
                // so that create works
                "check_callback": true,
                'data': [node]
            },
            search: {
                "case_insensitive": false,
                "show_only_matches": true,
                "show_only_matches_children": true,
                "fuzzy": true,
                search_callback: function(str, node) {

                    return node.text.toLowerCase().indexOf(str.toLowerCase()) !== -1;
                }
            },

            "types": {
                "default": {
                    "icon": "fa fa-folder icon-state-warning icon-lg"
                },
                "file": {
                    "icon": "fa fa-file icon-state-warning icon-lg"
                },
                "#": {
                    "valid_children": ["branch"]
                },
                "branch": {
                    "valid_children": ["leaf"]
                },
                "leaf": {
                    "valid_children": []
                }
            },
            "state": { "key": "demo2" },
            "plugins": ["contextmenu", "state", "types", "search"]
        }).on("move_node.jstree", function(node, nodes) {
            //Move
            //alert(nodes.node.id);
        });
        $('#jstreeSearch').keyup(function() {
            var to = false;
            if (to) {
                clearTimeout(to);
            }
            to = setTimeout(function() {
                var v = $('#jstreeSearch').val();
                $('#Menu').jstree(true).search(v);
            }, 250);
        });
    }

       
    </script>


}